# Generated by Django 4.2.4 on 2023-09-02 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_setup', '0002_appdpsetup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appdpsetup',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Setup'},
        ),
        migrations.AddField(
            model_name='menulink',
            name='DPSetup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_setup.appdpsetup'),
        ),
    ]
