# Generated by Django 4.2.4 on 2023-09-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_setup', '0004_rename_appdpsetup_designpatternsetup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpatternsetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
